
#branches:
# only:
# - master
# - develop

language: objective-c
osx_image: xcode8.2

before_install:
  - cd ./Source

script:
  - xcodebuild -project Listenable.xcodeproj -scheme Listenable -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
